import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/styles/globals.css";
import { Toaster } from "@/src/components/ui/toaster";
import Link from "next/link";
import { MainNav } from "~/components/main-nav";
import { buttonVariants } from "~/components/ui/button";
import { cn } from "~/utils/form-handling";
import { Icons } from "~/components/icons";
import { Header } from "~/components/header";
import * as Separator from "@radix-ui/react-separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="justify-content-center flex min-h-screen flex-col ">
      <Header />
      <hr className="mx-auto h-2 w-full max-w-7xl stroke-slate-50"></hr>
      <main className="flex-1">{children}</main>
    </div>
  );
}
